// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buhfuaxrtaozpqlxgerj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aGZ1YXhydGFvenBxbHhnZXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjQyMzYsImV4cCI6MjA2Nzc0MDIzNn0.RH2Vg9dk3nw5FkOOrdU4mMZGS2GUMP4g2PIQbdJjU64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
